import { MoodOption, ThemeOption } from '../types';

export const MOOD_OPTIONS: MoodOption[] = [
  {
    id: 'calm',
    label: 'Calm & Grounded',
    emoji: '🌸',
    quote: 'Peace like floating petals on quiet warm water.',
    color: 'var(--theme-primary)',
    bgLight: 'var(--theme-badge-bg)',
    border: 'var(--theme-border)',
  },
  {
    id: 'cozy',
    label: 'Cozy Latte',
    emoji: '☕',
    quote: 'Warm mug in two hands, safe in this present moment.',
    color: 'var(--theme-primary)',
    bgLight: 'var(--theme-badge-bg)',
    border: 'var(--theme-border)',
  },
  {
    id: 'inspired',
    label: 'Inspired Bloom',
    emoji: '✨',
    quote: 'Fresh thoughts blooming with quiet morning clarity.',
    color: 'var(--theme-primary)',
    bgLight: 'var(--theme-badge-bg)',
    border: 'var(--theme-border)',
  },
  {
    id: 'tender',
    label: 'Tender Rain',
    emoji: '🌧️',
    quote: 'Allowing the gentle rain to nurture tomorrow’s buds.',
    color: 'var(--theme-text-muted)',
    bgLight: 'var(--theme-badge-bg)',
    border: 'var(--theme-border)',
  },
  {
    id: 'reflective',
    label: 'Pensive Roast',
    emoji: '🍂',
    quote: 'Listening to the quiet echoes of thoughts and feelings.',
    color: 'var(--theme-secondary)',
    bgLight: 'var(--theme-badge-bg)',
    border: 'var(--theme-border)',
  },
  {
    id: 'grateful',
    label: 'Heart Blossom',
    emoji: '💖',
    quote: 'Counting the sweet sprinkles of grace today.',
    color: 'var(--theme-accent)',
    bgLight: 'var(--theme-badge-bg)',
    border: 'var(--theme-border)',
  },
];

export const THEME_OPTIONS: ThemeOption[] = [
  {
    id: 'vibrant-palette',
    name: 'Bloom & Brew',
    description: 'Warm roasted espresso #6D4C41, sweet sakura cherry blossom, and porcelain milk canvas',
    primary: '#6D4C41',
    secondary: '#3E2723',
    accent: '#E57399',
    bgCanvas: '#FFF8F9',
    cardBg: '#FFFFFF',
    textHeading: '#3E2723',
    textBody: '#5D4037',
    textMuted: '#8D6E63',
    badgeBg: '#FDF1F3',
    borderColor: '#FCE4EC',
    subtleBorder: '#EED7D1',
    glowColor: 'rgba(109, 76, 65, 0.18)',
    particleColors: ['#FCE4EC', '#F8BBD0', '#E0C3B5', '#6D4C41'],
    gradient: 'linear-gradient(135deg, #6D4C41 0%, #E57399 50%, #E0C3B5 100%)',
  },
  {
    id: 'kyoto-matcha',
    name: 'Kyoto Matcha & Sakura',
    description: 'Ceremonial Kyoto matcha, fresh bamboo cream, and delicate pink cherry blossom buds',
    primary: '#3E6B48',
    secondary: '#1E3524',
    accent: '#E87A90',
    bgCanvas: '#F4F8F4',
    cardBg: '#FFFFFF',
    textHeading: '#1E3524',
    textBody: '#2D4532',
    textMuted: '#5F7E65',
    badgeBg: '#EAF3EB',
    borderColor: '#D4E5D5',
    subtleBorder: '#C3D8C5',
    glowColor: 'rgba(62, 107, 72, 0.2)',
    particleColors: ['#D4E5D5', '#E87A90', '#A3C9A8', '#3E6B48'],
    gradient: 'linear-gradient(135deg, #3E6B48 0%, #E87A90 50%, #A3C9A8 100%)',
  },
  {
    id: 'golden-chai',
    name: 'Golden Chai & Spiced Honey',
    description: 'Warm roasted spiced chai, whipped vanilla cream, honeyed parchment, and cinnamon stick',
    primary: '#B45309',
    secondary: '#451A03',
    accent: '#D97706',
    bgCanvas: '#FFFBEB',
    cardBg: '#FFFFFF',
    textHeading: '#451A03',
    textBody: '#78350F',
    textMuted: '#92400E',
    badgeBg: '#FEF3C7',
    borderColor: '#FDE68A',
    subtleBorder: '#FCD34D',
    glowColor: 'rgba(180, 83, 9, 0.2)',
    particleColors: ['#FEF3C7', '#FDE68A', '#F59E0B', '#B45309'],
    gradient: 'linear-gradient(135deg, #B45309 0%, #F59E0B 50%, #FCD34D 100%)',
  },
  {
    id: 'lavender-earl-grey',
    name: 'Lavender Earl Grey & Oat Fog',
    description: 'Calming French lavender blossom, steeped Earl Grey tea, and silky oat foam mist',
    primary: '#6D4C8C',
    secondary: '#2E183B',
    accent: '#B886D9',
    bgCanvas: '#FAF7FC',
    cardBg: '#FFFFFF',
    textHeading: '#2E183B',
    textBody: '#4E3863',
    textMuted: '#7E6796',
    badgeBg: '#F3ECF8',
    borderColor: '#E8DAF0',
    subtleBorder: '#DCBFE8',
    glowColor: 'rgba(109, 76, 140, 0.2)',
    particleColors: ['#F3ECF8', '#E8DAF0', '#B886D9', '#6D4C8C'],
    gradient: 'linear-gradient(135deg, #6D4C8C 0%, #B886D9 50%, #DCBFE8 100%)',
  },
  {
    id: 'midnight-mocha',
    name: 'Midnight Mocha & Velvet Rose',
    description: 'Dark Belgian cocoa, roasted espresso beans, crushed candied rose petals, and twilight glow',
    primary: '#88304E',
    secondary: '#240B16',
    accent: '#E26D8C',
    bgCanvas: '#FCF6F8',
    cardBg: '#FFFFFF',
    textHeading: '#240B16',
    textBody: '#482434',
    textMuted: '#7D5365',
    badgeBg: '#FBEBF1',
    borderColor: '#F7D6E2',
    subtleBorder: '#EEBACD',
    glowColor: 'rgba(136, 48, 78, 0.22)',
    particleColors: ['#FBEBF1', '#F7D6E2', '#E26D8C', '#88304E'],
    gradient: 'linear-gradient(135deg, #88304E 0%, #E26D8C 50%, #240B16 100%)',
  },
  {
    id: 'butterfly-pea',
    name: 'Ocean Breeze & Butterfly Pea',
    description: 'Vibrant butterfly pea tea, crisp ocean seafoam, blueberry mist, and cool garden mint',
    primary: '#2B6CB0',
    secondary: '#152A4A',
    accent: '#38B2AC',
    bgCanvas: '#F2F9FD',
    cardBg: '#FFFFFF',
    textHeading: '#152A4A',
    textBody: '#23456F',
    textMuted: '#50769D',
    badgeBg: '#E6F4FB',
    borderColor: '#CCE7F7',
    subtleBorder: '#B5DBF2',
    glowColor: 'rgba(43, 108, 176, 0.2)',
    particleColors: ['#E6F4FB', '#CCE7F7', '#38B2AC', '#2B6CB0'],
    gradient: 'linear-gradient(135deg, #2B6CB0 0%, #38B2AC 50%, #CCE7F7 100%)',
  },
];
